var cryoVal=['T_Bolo', 'P_regul', 'T_Speer', //'T_PT1', 
                'T_B1K', 'P_B1K', 'T_PE1K',
                      'P_injection', 'debit', 'I_Alim1', 'I_Alim2',
                      'I_Alim3', 'I_Alim4',//'GM_P', 'PT_P', 'Pt_1',
                      'Pt_2',// 'Pt_3', 
                      'Hc1', 'Hc2', 'Hc3', 'Hc4',
                      'T_100K',
                      'T_50K',
                      'Ba_grotte',
                      'Ba_nemo',
                      'Co_France',
                      'Co_Italie',
                      'GM1_Power',
                      'Pt2_GM2_GM3_Power',
                      'GM2_50K',
                      'GM3_100K',
                      'circu',
                      'Pcircu',
                      'Tcircu',
                      'Tcl1',
                      'Tcl2',
                      'Tcl3',
                      'Tcl4',
                    ];

var cryoDescriptions = {
  'T_Bolo':'T of the bolo plate (K)', 
  'P_regul':'regulation power on the bolo plate (microW)', 
  'T_Speer':'T of the mixing chamber (K)', 
//  'T_PT1':'', 
  'T_B1K':'T of the 1K plate (K)', 
  'T_PE1K':'T of the Polyethylene at the 1K level (K)'
  'P_B1K':'pressure on the He4 pumping line on the 1K box (mbar)',
  'P_injection':'injection pressure of the He3 in the dilution circuit (mbar)', 
  'debit':'rate of He3 in the dilution circuit (micromol/s)', 
  'I_Alim1':'current on the BB power supply (top left) (A)', 
  'I_Alim2':'current on the BB power supply (bottom left) (A)',
  'I_Alim3':'current on the BB power supply (top right) (A)', 
  'I_Alim4':'current on the BB power supply (bottom left) (A)', 
//  'GM_P':'', 
//  'PT_P':'', 
//  'Pt_1':'',
  'Pt_2':'power supply of the Pulse Tube 2 (50K screen)', 
//  'Pt_3':'', 
  'Hc1':'height1 of the cryostat (mm)', 
  'Hc2':'height2 of the cryostat (mm)', 
  'Hc3':'height3 of the cryostat (mm)', 
  'Hc4':'height4 of the cryostat (mm)',
  'T_100K':'T of the 100K screen, cold electronics (K), for info it replaces the old T_PT1',
'T_50K':'T of the 50K screen (K)',
'Ba_grotte':'Ba calibration source',
'Ba_nemo':'Ba calibration source',
'Co_France':'Co calibration and regeneration source',
'Co_Italie':'Co calibration and regeneration source',
'GM1_Power':'Power of the GM1 (4K reliquefier)',
'Pt2_GM2_GM3_Power':'Main power of the PT2, GM2 and GM3 machines',
'GM2_50K':'Power on the GM2 (2nd machine on the cryoline)',
'GM3_100K':'Power on the GM2 (1rst machine on the cryoline)',
'circu':'Power on the circulator pump on the cryoline (percentage of full power)',
'Pcircu':'He4 pressure on the cryoline (bar)',
'Tcircu':'T of the circulator (C)',
'Tcl1':'He4 output of GM3 (K)',
'Tcl2':'He4 output of GM2 (K)',
'Tcl3':'He4 output of exchanger',
'Tcl4':'He4 input of exchanger'
};